import type { Country } from './types';
type CountryProfile = {
  label: string; queries: string[]; legal: RegExp; country: RegExp;
  candidateSearch: { regionCode: Country; placeName: string; keywords: readonly string[]; defaults: string[] };
};
const english = ['matcha importer', 'matcha distributor', 'matcha wholesaler'];
export const countryProfiles: Record<Country, CountryProfile> = {
  US: { label: 'USA', queries: ['Japanese matcha wholesaler USA', 'matcha importer USA', 'matcha foodservice USA'], legal: /about|contact|company|legal/i, country: /\b(?:USA|U\.S\.A\.?|United States)\b/i,
    candidateSearch: { regionCode: 'US', placeName: 'United States', keywords: [...english, 'Japanese matcha importer', 'Japanese matcha distributor', 'Japanese green tea importer', 'matcha supplier', 'wholesale matcha', 'bulk matcha'], defaults: ['matcha importer', 'matcha distributor', 'Japanese green tea importer'] } },
  FR: { label: 'France', queries: ['importateur matcha japonais France', 'grossiste matcha France', 'matcha professionnel France'], legal: /mentions[-\s_]?l[eé]gales|contact|soci[eé]t[eé]/i, country: /\bFrance\b/i,
    candidateSearch: { regionCode: 'FR', placeName: 'France', keywords: [...english, 'grossiste matcha', 'importateur matcha', 'fournisseur matcha'], defaults: ['matcha importer', 'grossiste matcha', 'importateur matcha'] } },
  DE: { label: 'Germany', queries: ['Japan Matcha Großhandel Deutschland', 'Matcha Importeur Deutschland', 'Matcha Gastronomie Deutschland'], legal: /impressum|imprint|kontakt/i, country: /\b(?:Germany|Deutschland)\b/i,
    candidateSearch: { regionCode: 'DE', placeName: 'Germany', keywords: [...english, 'Matcha Großhandel', 'Matcha Importeur', 'japanischer Matcha Großhandel'], defaults: ['matcha importer', 'Matcha Großhandel', 'Matcha Importeur'] } },
  NL: { label: 'Netherlands', queries: ['matcha groothandel Nederland', 'matcha importeur Nederland'], legal: /about|contact|company|legal|over-ons|algemene-voorwaarden/i, country: /\b(?:Netherlands|Nederland)\b/i,
    candidateSearch: { regionCode: 'NL', placeName: 'Netherlands', keywords: [...english, 'matcha groothandel', 'matcha importeur', 'Japanese matcha supplier'], defaults: ['matcha importer', 'matcha groothandel', 'matcha importeur'] } },
  TH: { label: 'Thailand', queries: ['matcha importer Thailand', 'ขายส่งมัทฉะ Thailand'], legal: /about|contact|company|legal|เกี่ยวกับ|ติดต่อ/i, country: /\bThailand\b|ประเทศไทย/i,
    candidateSearch: { regionCode: 'TH', placeName: 'Thailand', keywords: [...english, 'ผู้นำเข้ามัทฉะ', 'ขายส่งมัทฉะ', 'ผู้นำเข้าชาญี่ปุ่น'], defaults: ['matcha importer', 'ขายส่งมัทฉะ', 'ผู้นำเข้าชาญี่ปุ่น'] } },
  KR: { label: 'South Korea', queries: ['matcha importer South Korea', '말차 도매 대한민국'], legal: /about|contact|company|legal|회사|문의/i, country: /\b(?:South Korea|Republic of Korea)\b|대한민국|한국/i,
    candidateSearch: { regionCode: 'KR', placeName: 'South Korea', keywords: [...english, '말차 수입업체', '말차 도매', '일본 녹차 수입업체'], defaults: ['matcha importer', '말차 도매', '일본 녹차 수입업체'] } },
  TW: { label: 'Taiwan', queries: ['matcha importer Taiwan', '抹茶批發 台灣'], legal: /about|contact|company|legal|關於|聯絡|联系/i, country: /\bTaiwan\b|臺灣|台灣/i,
    candidateSearch: { regionCode: 'TW', placeName: 'Taiwan', keywords: [...english, '抹茶進口商', '抹茶批發', '日本茶進口商'], defaults: ['matcha importer', '抹茶批發', '日本茶進口商'] } },
  IN: { label: 'India', queries: ['matcha supplier India', 'wholesale matcha India'], legal: /about|contact|company|legal/i, country: /\bIndia\b|भारत/i,
    candidateSearch: { regionCode: 'IN', placeName: 'India', keywords: [...english, 'matcha supplier', 'wholesale matcha', 'Japanese tea importer'], defaults: ['matcha importer', 'matcha supplier', 'wholesale matcha'] } },
  VN: { label: 'Vietnam', queries: ['nhà phân phối matcha Việt Nam', 'matcha bán sỉ Việt Nam'], legal: /about|contact|company|legal|giới-thiệu|gioi-thieu|liên-hệ|lien-he/i, country: /\b(?:Vietnam|Viet Nam)\b|Việt Nam/i,
    candidateSearch: { regionCode: 'VN', placeName: 'Vietnam', keywords: [...english, 'nhà nhập khẩu matcha', 'nhà phân phối matcha', 'matcha bán sỉ'], defaults: ['matcha importer', 'nhà phân phối matcha', 'matcha bán sỉ'] } },
  IT: { label: 'Italy', queries: ['importatore matcha Italia', 'matcha ingrosso Italia'], legal: /about|contact|company|legal|chi-siamo|contatti|note-legali/i, country: /\b(?:Italy|Italia)\b/i,
    candidateSearch: { regionCode: 'IT', placeName: 'Italy', keywords: [...english, 'importatore matcha', 'matcha ingrosso', 'fornitore matcha'], defaults: ['matcha importer', 'importatore matcha', 'matcha ingrosso'] } },
  ES: { label: 'Spain', queries: ['importador matcha España', 'matcha al por mayor España'], legal: /about|contact|company|legal|quienes-somos|contacto|aviso-legal/i, country: /\b(?:Spain|España)\b/i,
    candidateSearch: { regionCode: 'ES', placeName: 'Spain', keywords: [...english, 'importador matcha', 'matcha al por mayor', 'proveedor matcha'], defaults: ['matcha importer', 'importador matcha', 'matcha al por mayor'] } },
  BE: { label: 'Belgium', queries: ['grossiste matcha Belgique', 'matcha groothandel België'], legal: /about|contact|company|legal|mentions-legales|over-ons|algemene-voorwaarden/i, country: /\b(?:Belgium|Belgique|België|Belgien)\b/i,
    candidateSearch: { regionCode: 'BE', placeName: 'Belgium', keywords: [...english, 'grossiste matcha', 'matcha groothandel', 'importateur matcha'], defaults: ['matcha importer', 'grossiste matcha', 'matcha groothandel'] } },
  AT: { label: 'Austria', queries: ['Matcha Importeur Österreich', 'Matcha Großhandel Österreich'], legal: /about|contact|company|legal|impressum|kontakt/i, country: /\bAustria\b|Österreich/i,
    candidateSearch: { regionCode: 'AT', placeName: 'Austria', keywords: [...english, 'Matcha Importeur', 'Matcha Großhandel', 'japanischer Matcha Großhandel'], defaults: ['matcha importer', 'Matcha Importeur', 'Matcha Großhandel'] } },
  PL: { label: 'Poland', queries: ['importer matcha Polska', 'matcha hurt Polska'], legal: /about|contact|company|legal|o-nas|kontakt|regulamin/i, country: /\bPoland\b|Polska/i,
    candidateSearch: { regionCode: 'PL', placeName: 'Poland', keywords: [...english, 'importer matcha', 'matcha hurt', 'hurtownia matcha'], defaults: ['matcha importer', 'importer matcha', 'matcha hurt'] } },
  IE: { label: 'Ireland', queries: ['matcha importer Ireland', 'matcha wholesaler Ireland'], legal: /about|contact|company|legal|terms/i, country: /\bIreland\b|Éire/i,
    candidateSearch: { regionCode: 'IE', placeName: 'Ireland', keywords: [...english, 'matcha supplier', 'wholesale matcha', 'Japanese green tea importer'], defaults: ['matcha importer', 'matcha distributor', 'matcha wholesaler'] } },
  PT: { label: 'Portugal', queries: ['importador de matcha Portugal', 'matcha por grosso Portugal'], legal: /about|contact|company|legal|sobre|contacto|termos/i, country: /\bPortugal\b/i,
    candidateSearch: { regionCode: 'PT', placeName: 'Portugal', keywords: [...english, 'importador de matcha', 'matcha por grosso', 'fornecedor de matcha'], defaults: ['matcha importer', 'importador de matcha', 'matcha por grosso'] } },
  LU: { label: 'Luxembourg', queries: ['grossiste matcha Luxembourg', 'importateur matcha Luxembourg'], legal: /about|contact|company|legal|mentions-legales|impressum|kontakt/i, country: /\bLuxembourg\b|Lëtzebuerg/i,
    candidateSearch: { regionCode: 'LU', placeName: 'Luxembourg', keywords: [...english, 'grossiste matcha', 'importateur matcha', 'matcha groothandel'], defaults: ['matcha importer', 'grossiste matcha', 'importateur matcha'] } },
  DK: { label: 'Denmark', queries: ['matcha importør Danmark', 'matcha engros Danmark'], legal: /about|contact|company|legal|om-os|kontakt|handelsbetingelser/i, country: /\bDenmark\b|Danmark/i,
    candidateSearch: { regionCode: 'DK', placeName: 'Denmark', keywords: [...english, 'matcha importør', 'matcha engros', 'matcha leverandør'], defaults: ['matcha importer', 'matcha importør', 'matcha engros'] } },
  SE: { label: 'Sweden', queries: ['matcha importör Sverige', 'matcha grossist Sverige'], legal: /about|contact|company|legal|om-oss|kontakt|villkor/i, country: /\bSweden\b|Sverige/i,
    candidateSearch: { regionCode: 'SE', placeName: 'Sweden', keywords: [...english, 'matcha importör', 'matcha grossist', 'matcha leverantör'], defaults: ['matcha importer', 'matcha importör', 'matcha grossist'] } },
  FI: { label: 'Finland', queries: ['matcha maahantuoja Suomi', 'matcha tukkumyynti Suomi'], legal: /about|contact|company|legal|tietoa|yhteystiedot|ehdot/i, country: /\bFinland\b|Suomi/i,
    candidateSearch: { regionCode: 'FI', placeName: 'Finland', keywords: [...english, 'matcha maahantuoja', 'matcha toimittaja', 'Japanese green tea importer'], defaults: ['matcha importer', 'matcha maahantuoja', 'matcha toimittaja'] } },
  CZ: { label: 'Czech Republic', queries: ['dovozce matcha Česko', 'matcha velkoobchod Česko'], legal: /about|contact|company|legal|o-nas|kontakt|obchodni-podminky/i, country: /\b(?:Czech Republic|Czechia)\b|Česko/i,
    candidateSearch: { regionCode: 'CZ', placeName: 'Czech Republic', keywords: [...english, 'dovozce matcha', 'matcha velkoobchod', 'dodavatel matcha'], defaults: ['matcha importer', 'dovozce matcha', 'matcha velkoobchod'] } },
  SK: { label: 'Slovakia', queries: ['dovozca matcha Slovensko', 'matcha veľkoobchod Slovensko'], legal: /about|contact|company|legal|o-nas|kontakt|obchodne-podmienky/i, country: /\bSlovakia\b|Slovensko/i,
    candidateSearch: { regionCode: 'SK', placeName: 'Slovakia', keywords: [...english, 'dovozca matcha', 'matcha veľkoobchod', 'dodávateľ matcha'], defaults: ['matcha importer', 'dovozca matcha', 'matcha veľkoobchod'] } },
  HU: { label: 'Hungary', queries: ['matcha importőr Magyarország', 'matcha nagykereskedés Magyarország'], legal: /about|contact|company|legal|rolunk|kapcsolat|aszf/i, country: /\bHungary\b|Magyarország/i,
    candidateSearch: { regionCode: 'HU', placeName: 'Hungary', keywords: [...english, 'matcha importőr', 'matcha nagykereskedés', 'matcha beszállító'], defaults: ['matcha importer', 'matcha importőr', 'matcha nagykereskedés'] } },
  SI: { label: 'Slovenia', queries: ['uvoznik matcha Slovenija', 'matcha veleprodaja Slovenija'], legal: /about|contact|company|legal|o-nas|kontakt|pogoji/i, country: /\bSlovenia\b|Slovenija/i,
    candidateSearch: { regionCode: 'SI', placeName: 'Slovenia', keywords: [...english, 'uvoznik matcha', 'matcha veleprodaja', 'dobavitelj matcha'], defaults: ['matcha importer', 'uvoznik matcha', 'matcha veleprodaja'] } },
  HR: { label: 'Croatia', queries: ['uvoznik matcha Hrvatska', 'matcha veleprodaja Hrvatska'], legal: /about|contact|company|legal|o-nama|kontakt|uvjeti/i, country: /\bCroatia\b|Hrvatska/i,
    candidateSearch: { regionCode: 'HR', placeName: 'Croatia', keywords: [...english, 'uvoznik matcha', 'matcha veleprodaja', 'dobavljač matcha'], defaults: ['matcha importer', 'uvoznik matcha', 'matcha veleprodaja'] } },
  RO: { label: 'Romania', queries: ['importator matcha România', 'matcha en-gros România'], legal: /about|contact|company|legal|despre|contact|termeni/i, country: /\bRomania\b|România/i,
    candidateSearch: { regionCode: 'RO', placeName: 'Romania', keywords: [...english, 'importator matcha', 'matcha en-gros', 'furnizor matcha'], defaults: ['matcha importer', 'importator matcha', 'matcha en-gros'] } },
  BG: { label: 'Bulgaria', queries: ['вносител матча България', 'матча на едро България'], legal: /about|contact|company|legal|za-nas|kontakti|uslovi/i, country: /\bBulgaria\b|България/i,
    candidateSearch: { regionCode: 'BG', placeName: 'Bulgaria', keywords: [...english, 'вносител матча', 'матча на едро', 'доставчик матча'], defaults: ['matcha importer', 'вносител матча', 'матча на едро'] } },
  GR: { label: 'Greece', queries: ['εισαγωγέας matcha Ελλάδα', 'matcha χονδρική Ελλάδα'], legal: /about|contact|company|legal|sxetika|epikoinonia|oroi/i, country: /\bGreece\b|Ελλάδα/i,
    candidateSearch: { regionCode: 'GR', placeName: 'Greece', keywords: [...english, 'εισαγωγέας matcha', 'matcha χονδρική', 'προμηθευτής matcha'], defaults: ['matcha importer', 'εισαγωγέας matcha', 'matcha χονδρική'] } },
  CY: { label: 'Cyprus', queries: ['matcha importer Cyprus', 'matcha χονδρική Κύπρος'], legal: /about|contact|company|legal|sxetika|epikoinonia|oroi/i, country: /\bCyprus\b|Κύπρος/i,
    candidateSearch: { regionCode: 'CY', placeName: 'Cyprus', keywords: [...english, 'εισαγωγέας matcha', 'matcha χονδρική', 'προμηθευτής matcha'], defaults: ['matcha importer', 'matcha distributor', 'matcha χονδρική'] } },
  MT: { label: 'Malta', queries: ['matcha importer Malta', 'matcha wholesaler Malta'], legal: /about|contact|company|legal|terms/i, country: /\bMalta\b/i,
    candidateSearch: { regionCode: 'MT', placeName: 'Malta', keywords: [...english, 'matcha supplier', 'wholesale matcha', 'Japanese green tea importer'], defaults: ['matcha importer', 'matcha distributor', 'matcha wholesaler'] } },
  LT: { label: 'Lithuania', queries: ['matcha importuotojas Lietuva', 'matcha didmena Lietuva'], legal: /about|contact|company|legal|apie-mus|kontaktai|taisykles/i, country: /\bLithuania\b|Lietuva/i,
    candidateSearch: { regionCode: 'LT', placeName: 'Lithuania', keywords: [...english, 'matcha importuotojas', 'matcha didmena', 'matcha tiekėjas'], defaults: ['matcha importer', 'matcha importuotojas', 'matcha didmena'] } },
  LV: { label: 'Latvia', queries: ['matcha importētājs Latvija', 'matcha vairumtirdzniecība Latvija'], legal: /about|contact|company|legal|par-mums|kontakti|noteikumi/i, country: /\bLatvia\b|Latvija/i,
    candidateSearch: { regionCode: 'LV', placeName: 'Latvia', keywords: [...english, 'matcha importētājs', 'matcha vairumtirdzniecība', 'matcha piegādātājs'], defaults: ['matcha importer', 'matcha importētājs', 'matcha vairumtirdzniecība'] } },
  EE: { label: 'Estonia', queries: ['matcha importija Eesti', 'matcha hulgimüük Eesti'], legal: /about|contact|company|legal|meist|kontakt|tingimused/i, country: /\bEstonia\b|Eesti/i,
    candidateSearch: { regionCode: 'EE', placeName: 'Estonia', keywords: [...english, 'matcha importija', 'matcha hulgimüük', 'matcha tarnija'], defaults: ['matcha importer', 'matcha importija', 'matcha hulgimüük'] } },
};
export function isCountry(value: unknown): value is Country { return typeof value === 'string' && Object.hasOwn(countryProfiles, value); }
